/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var parser = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,6],$V1=[1,7],$V2=[1,8],$V3=[1,9],$V4=[1,10],$V5=[1,11],$V6=[1,12],$V7=[1,13],$V8=[1,14],$V9=[1,15],$Va=[1,16],$Vb=[1,17],$Vc=[1,18],$Vd=[1,19],$Ve=[1,20],$Vf=[1,21],$Vg=[1,22],$Vh=[1,23],$Vi=[1,24],$Vj=[1,25],$Vk=[1,26],$Vl=[1,27],$Vm=[1,28],$Vn=[1,29],$Vo=[1,30],$Vp=[4,6,8,10,11,12,13,15,16,17,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"program":3,"EOF":4,"instructions":5,"EOL":6,"instruction":7,"T_PUSH":8,"T_NUMBER":9,"T_SWAP":10,"T_DUB":11,"T_DROP":12,"T_OUT":13,"T_REG":14,"T_ADD":15,"T_SUB":16,"T_JMP":17,"T_NAME":18,"T_HALT":19,"T_PRINT":20,"T_STRING":21,"T_POP":22,"T_LABEL":23,"T_CALL":24,"T_RET":25,"T_MUL":26,"T_DIV":27,"T_INC":28,"T_DEC":29,"T_LOOP":30,"T_NEXT":31,"T_IN":32,"T_JE":33,"T_JNE":34,"T_MOV":35,"T_CMP":36,"$accept":0,"$end":1},
terminals_: {2:"error",4:"EOF",6:"EOL",8:"T_PUSH",9:"T_NUMBER",10:"T_SWAP",11:"T_DUB",12:"T_DROP",13:"T_OUT",14:"T_REG",15:"T_ADD",16:"T_SUB",17:"T_JMP",18:"T_NAME",19:"T_HALT",20:"T_PRINT",21:"T_STRING",22:"T_POP",23:"T_LABEL",24:"T_CALL",25:"T_RET",26:"T_MUL",27:"T_DIV",28:"T_INC",29:"T_DEC",30:"T_LOOP",31:"T_NEXT",32:"T_IN",33:"T_JE",34:"T_JNE",35:"T_MOV",36:"T_CMP"},
productions_: [0,[3,1],[3,2],[5,1],[5,1],[5,2],[5,2],[7,2],[7,1],[7,1],[7,1],[7,1],[7,2],[7,1],[7,3],[7,3],[7,1],[7,3],[7,3],[7,2],[7,1],[7,2],[7,2],[7,2],[7,1],[7,2],[7,1],[7,1],[7,3],[7,3],[7,1],[7,3],[7,3],[7,1],[7,2],[7,1],[7,2],[7,2],[7,1],[7,1],[7,2],[7,2],[7,2],[7,3],[7,3],[7,3],[7,3]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 2:

        return $$[$0-1];
    
break;
case 4:

        this.$ = $$[$0]
    
break;
case 6:

        this.$ = $$[$0];
    
break;
case 7:

        this.$ = asm.pushi($$[$0]) 
    
break;
case 8:

        this.$ = asm.swap();
    
break;
case 9:

        this.$ = asm.dub();
    
break;
case 10:

        this.$ = asm.drop();
    
break;
case 11:

        this.$ = asm.out();
    
break;
case 12:

        this.$ = asm.outr($$[$0]);
    
break;
case 13:

        this.$ = asm.add();
    
break;
case 14:

        this.$ = asm.addrr($$[$0-1], $$[$0]);
    
break;
case 15:

        this.$ = asm.addri($$[$0-1], $$[$0]);
    
break;
case 16:

        this.$ = asm.sub();
    
break;
case 17:

        this.$ = asm.subrr($$[$0-1], $$[$0]);
    
break;
case 18:

        this.$ = asm.subri($$[$0-1], $$[$0]);
    
break;
case 19:

        this.$ = asm.jmp($$[$0]);
    
break;
case 20:

        this.$ = asm.halt();
    
break;
case 21:

        this.$ = asm.print($$[$0]);
    
break;
case 22:

        this.$ = asm.pushr($$[$0]);
    
break;
case 23:

        this.$ = asm.pop($$[$0]);
    
break;
case 24:

        this.$ = asm.label($$[$0]);
    
break;
case 25:

        this.$ = asm.call($$[$0]);
    
break;
case 26:

        this.$ = asm.ret();
    
break;
case 27:

        this.$ = asm.mul();
    
break;
case 28:

        this.$ = asm.mulrr($$[$0-1], $$[$0]);
    
break;
case 29:

        this.$ = asm.mulri($$[$0-1], $$[$0]);
    
break;
case 30:

        this.$ = asm.div();
    
break;
case 31:

        this.$ = asm.divrr($$[$0-1], $$[$0]);
    
break;
case 32:

        this.$ = asm.divri($$[$0-1], $$[$0]);
    
break;
case 33:

        this.$ = asm.inc();
    
break;
case 34:

        this.$ = asm.incr($$[$0]);
    
break;
case 35:

        this.$ = asm.dec();
    
break;
case 36:

        this.$ = asm.decr();
    
break;
case 37:

        this.$ = asm.loop($$[$0]);
    
break;
case 38:

        this.$ = asm.next();
    
break;
case 39:

        this.$ = asm.read();
    
break;
case 40:

        this.$ = asm.readr($$[$0]);
    
break;
case 41:

        this.$ = asm.je($$[$0]);
    
break;
case 42:

        this.$ = asm.jne($$[$0]);
    
break;
case 43:

        this.$ = asm.movri($$[$0-1], $$[$0]);
    
break;
case 44:

        this.$ = asm.movrr($$[$0-1], $$[$0]);
    
break;
case 45:

        this.$ = asm.cmprr($$[$0-1], $$[$0]);
    
break;
case 46:

        this.$ = asm.cmpri($$[$0-1], $$[$0]);
    
break;
}
},
table: [{3:1,4:[1,2],5:3,6:[1,4],7:5,8:$V0,10:$V1,11:$V2,12:$V3,13:$V4,15:$V5,16:$V6,17:$V7,19:$V8,20:$V9,22:$Va,23:$Vb,24:$Vc,25:$Vd,26:$Ve,27:$Vf,28:$Vg,29:$Vh,30:$Vi,31:$Vj,32:$Vk,33:$Vl,34:$Vm,35:$Vn,36:$Vo},{1:[3]},{1:[2,1]},{4:[1,31],6:[1,32],7:33,8:$V0,10:$V1,11:$V2,12:$V3,13:$V4,15:$V5,16:$V6,17:$V7,19:$V8,20:$V9,22:$Va,23:$Vb,24:$Vc,25:$Vd,26:$Ve,27:$Vf,28:$Vg,29:$Vh,30:$Vi,31:$Vj,32:$Vk,33:$Vl,34:$Vm,35:$Vn,36:$Vo},o($Vp,[2,3]),o($Vp,[2,4]),{9:[1,34],14:[1,35]},o($Vp,[2,8]),o($Vp,[2,9]),o($Vp,[2,10]),o($Vp,[2,11],{14:[1,36]}),o($Vp,[2,13],{14:[1,37]}),o($Vp,[2,16],{14:[1,38]}),{18:[1,39]},o($Vp,[2,20]),{21:[1,40]},{14:[1,41]},o($Vp,[2,24]),{18:[1,42]},o($Vp,[2,26]),o($Vp,[2,27],{14:[1,43]}),o($Vp,[2,30],{14:[1,44]}),o($Vp,[2,33],{14:[1,45]}),o($Vp,[2,35],{14:[1,46]}),{9:[1,47]},o($Vp,[2,38]),o($Vp,[2,39],{14:[1,48]}),{18:[1,49]},{18:[1,50]},{14:[1,51]},{14:[1,52]},{1:[2,2]},o($Vp,[2,5]),o($Vp,[2,6]),o($Vp,[2,7]),o($Vp,[2,22]),o($Vp,[2,12]),{9:[1,54],14:[1,53]},{9:[1,56],14:[1,55]},o($Vp,[2,19]),o($Vp,[2,21]),o($Vp,[2,23]),o($Vp,[2,25]),{9:[1,58],14:[1,57]},{9:[1,60],14:[1,59]},o($Vp,[2,34]),o($Vp,[2,36]),o($Vp,[2,37]),o($Vp,[2,40]),o($Vp,[2,41]),o($Vp,[2,42]),{9:[1,61],14:[1,62]},{9:[1,64],14:[1,63]},o($Vp,[2,14]),o($Vp,[2,15]),o($Vp,[2,17]),o($Vp,[2,18]),o($Vp,[2,28]),o($Vp,[2,29]),o($Vp,[2,31]),o($Vp,[2,32]),o($Vp,[2,43]),o($Vp,[2,44]),o($Vp,[2,45]),o($Vp,[2,46])],
defaultActions: {2:[2,1],31:[2,2]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

    const Assembler = require('./assembler');
    const asm = new Assembler();
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:return 6;             
break;
case 1:/* skip whitespace */      
break;
case 2:return 6;
break;
case 3:yy_.yytext = yy_.yytext.substr(0,yy_.yyleng-1); return 23;
break;
case 4:return 10;
break;
case 5:return 11;
break;
case 6:return 13;
break;
case 7:return 15;
break;
case 8:return 16;
break;
case 9:return 17;  
break;
case 10:return 19; 
break;
case 11:return 20;
break;
case 12:return 8;
break;
case 13:return 22;
break;
case 14:return 24;
break;
case 15:return 25;
break;
case 16:return 26;
break;
case 17:return 27;
break;
case 18:return 28;
break;
case 19:return 29;
break;
case 20:return 12;
break;
case 21:return 30;
break;
case 22:return 31;
break;
case 23:return 32;
break;
case 24:return 33;
break;
case 25:return 34;
break;
case 26:return 35;
break;
case 27:return 36;
break;
case 28:yy_.yytext = +yy_.yytext.substr(1,yy_.yyleng-1); return 14;
break;
case 29:yy_.yytext = +yy_.yytext; return 9;
break;
case 30:yy_.yytext = yy_.yytext.charCodeAt(1); return 9;
break;
case 31:yy_.yytext = yy_.yytext.substr(1,yy_.yyleng-2); return 21;
break;
case 32:return 18;
break;
case 33:return 'INVALID';
break;
case 34:return 4;
break;
}
},
rules: [/^(?:;[^\n]*[^\n]+)/,/^(?:[  \t]+)/,/^(?:[\n]+)/,/^(?:(([_a-zA-Z0-9*?]+):))/,/^(?:swap\b)/,/^(?:dub\b)/,/^(?:out\b)/,/^(?:add\b)/,/^(?:sub\b)/,/^(?:jmp\b)/,/^(?:halt\b)/,/^(?:print\b)/,/^(?:push\b)/,/^(?:pop\b)/,/^(?:call\b)/,/^(?:ret\b)/,/^(?:mul\b)/,/^(?:div\b)/,/^(?:inc\b)/,/^(?:dec\b)/,/^(?:drop\b)/,/^(?:loop\b)/,/^(?:next\b)/,/^(?:in\b)/,/^(?:je\b)/,/^(?:jne\b)/,/^(?:mov\b)/,/^(?:cmp\b)/,/^(?:r0|r1|r2|r3|r4\b)/,/^(?:([0-9]+))/,/^(?:('[^\']*'))/,/^(?:("[^\"]*"))/,/^(?:([_a-zA-Z0-9*?]+))/,/^(?:.)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = parser;
exports.Parser = parser.Parser;
exports.parse = function () { return parser.parse.apply(parser, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}